name: 'Get version'
description: '获取个人规则版本号'
inputs:
  date:
    required: false
    description: 传入就使用这个时间 否则使用当前时间
  
outputs:
  version:
    description: "个人规则版本号"
    value: ${{ steps.version-generator.outputs.version }}
runs:
  using: "composite"
  steps:
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 8
    - id: version-generator-default
      if: ${{ inputs.date == null }}
      run: |
        export TZ='Asia/Shanghai'
        DATE=$(date +'%Y%m%d')
        export ORIGIN_REF_NAME=${{ github.ref_name }}
        export REF_NAME=${ORIGIN_REF_NAME//\//\_}
        echo "version=$DATE-$REF_NAME-${{ steps.short-sha.outputs.sha }}" >> $GITHUB_OUTPUT
      shell: bash
    - id: version-generator-default
      if: ${{ inputs.date != null }}
      run: |
        export TZ='Asia/Shanghai'
        USE_DATE="${{ inputs.date }}"
        DATE=$(date -d $USE_DATE +"%Y%m%d")
        export ORIGIN_REF_NAME=${{ github.ref_name }}
        export REF_NAME=${ORIGIN_REF_NAME//\//\_}
        echo "version=$DATE-$REF_NAME-${{ steps.short-sha.outputs.sha }}" >> $GITHUB_OUTPUT
      shell: bash
