name: 'Get version'
description: '获取个人规则版本号'
outputs:
  version:
    description: "个人规则版本号"
    value: ${{ steps.version-generator.outputs.version }}
runs:
  using: "composite"
  steps:
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 8
    - id: version-generator
      run: |
        export TZ='Asia/Shanghai'
        DATE=$(date +'%Y%m%d')
        export ORIGIN_REF_NAME=${{ github.ref_name }}
        export REF_NAME=${ORIGIN_REF_NAME//\//\_}
        echo "version=$DATE-$REF_NAME-${{ steps.short-sha.outputs.sha }}" >> $GITHUB_OUTPUT
      shell: bash
