name: Test

on:
  push:
    branches:
      - "main"

jobs:
  test-get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: 0xTeams/get-version-action@main
        id: get-version
      - run: echo ${{ steps.get-version.outputs.version }}